pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Hello..'
            }
        }
        stage('Test') {
            steps {
                echo 'It's Me..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Goodbye....'
            }
        }
    }
}
