pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo "Hello.."'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Its Me.."'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Goodbye..."'
            }
        }
    }
}

